name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  HSM:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cypress dependencies
        run: npm ci

      - name: Set executable permissions for Cypress binary
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Upload Cypress artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots,cypress/videos
